---
language: node_js
node_js:
  - 12
  - 10
  - 8
cache:
  directories:
    - ~/.npm
before_install:
  - npm install -g npm@latest
install:
  - npm audit || echo 'Make it unblocking awaiting tar/node-gyp fix'
  - npm ci
script:
  - npx commitlint-travis
  - npm run test -- --serial
after_success:
  - npm run codecov
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release --dry-run --branch develop
    on:
      node: 10
      branch: develop
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release --branch master
    on:
      branch: master
      node: 10
