---
language: node_js
node_js:
  - 12
  - 10
  - 8
cache:
  directories:
    - ~/.npm
before_install:
  - npm install -g npm@latest
install:
  - npm audit
  - npm ci
script:
  - npx commitlint-travis
  - npm run lint
  - npm run test -- --serial
after_success:
  - npx codecov -f coverage/coverage-final.json
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release --dry-run --branch develop
    on:
      node: 12
      branch: develop
  - provider: script
    skip_cleanup: true
    script:
      - npx semantic-release --branch master
    on:
      branch: master
      node: 12
