---
language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - $HOME/.npm
before_install:
  - npm install -g npm@latest
install:
  - npm install
script:
  - npm test
after_success:
  - npm run codecov
